In [1]:
# things we need for NLP
import nltk
from nltk.stem.lancaster import LancasterStemmer
stemmer = LancasterStemmer()

In [2]:
# things we need for Tensorflow
import numpy as np
import keras
import tensorflow as tf
from sklearn.linear_model import LogisticRegression
import random
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

Using TensorFlow backend.
/Users/swapnilpote/.virtualenvs/py3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [3]:
# import our chat-bot intents file
import json
with open('intents.json') as json_data:
    intents = json.load(json_data)

In [4]:
intents

{'intents': [{'context_set': '',
   'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day'],
   'responses': ['Hello, thanks for visiting',
    'Good to see you again',
    'Hi there, how can I help?'],
   'tag': 'greeting'},
  {'patterns': ['Bye', 'See you later', 'Goodbye'],
   'responses': ['See you later, thanks for visiting',
    'Have a nice day',
    'Bye! Come back again soon.'],
   'tag': 'goodbye'},
  {'patterns': ['Thanks', 'Thank you', "That's helpful"],
   'responses': ['Happy to help!', 'Any time!', 'My pleasure'],
   'tag': 'thanks'},
  {'patterns': ['What hours are you open?',
    'What are your hours?',
    'When are you open?'],
   'responses': ["We're open every day 9am-9pm",
    'Our hours are 9am-9pm every day'],
   'tag': 'hours'},
  {'patterns': ['Which mopeds do you have?',
    'What kinds of mopeds are there?',
    'What do you rent?'],
   'responses': ['We rent Yamaha, Piaggio and Vespa mopeds',
    'We have Piaggio, Vespa and Yamaha mopeds'

In [6]:
X = []
y = []

In [8]:
for doc in intents['intents']:
    print(doc['tag'])
    for p in doc['patterns']:
        print(p)
        X.append(p)
        y.append(doc['tag'])

greeting
Hi
How are you
Is anyone there?
Hello
Good day
goodbye
Bye
See you later
Goodbye
thanks
Thanks
Thank you
That's helpful
hours
What hours are you open?
What are your hours?
When are you open?
mopeds
Which mopeds do you have?
What kinds of mopeds are there?
What do you rent?
payments
Do you take credit cards?
Do you accept Mastercard?
Are you cash only?
opentoday
Are you open today?
When do you open today?
What are your hours today?
rental
Can we rent a moped?
I'd like to rent a moped
How does this work?
today
today


In [9]:
X

['Hi',
 'How are you',
 'Is anyone there?',
 'Hello',
 'Good day',
 'Bye',
 'See you later',
 'Goodbye',
 'Thanks',
 'Thank you',
 "That's helpful",
 'What hours are you open?',
 'What are your hours?',
 'When are you open?',
 'Which mopeds do you have?',
 'What kinds of mopeds are there?',
 'What do you rent?',
 'Do you take credit cards?',
 'Do you accept Mastercard?',
 'Are you cash only?',
 'Are you open today?',
 'When do you open today?',
 'What are your hours today?',
 'Can we rent a moped?',
 "I'd like to rent a moped",
 'How does this work?',
 'today']

In [10]:
y

['greeting',
 'greeting',
 'greeting',
 'greeting',
 'greeting',
 'goodbye',
 'goodbye',
 'goodbye',
 'thanks',
 'thanks',
 'thanks',
 'hours',
 'hours',
 'hours',
 'mopeds',
 'mopeds',
 'mopeds',
 'payments',
 'payments',
 'payments',
 'opentoday',
 'opentoday',
 'opentoday',
 'rental',
 'rental',
 'rental',
 'today']

# Convert text into numbers

In [11]:
cv = CountVectorizer()

In [13]:
X_cv = cv.fit_transform(X)

In [15]:
X_cv = X_cv.toarray()

In [17]:
X_cv.shape

(27, 46)

In [18]:
from sklearn.preprocessing import LabelEncoder

In [20]:
label_encoder_y = LabelEncoder()

In [21]:
y = label_encoder_y.fit_transform(y)

In [22]:
y

array([1, 1, 1, 1, 1, 0, 0, 0, 7, 7, 7, 2, 2, 2, 3, 3, 3, 5, 5, 5, 4, 4, 4,
       6, 6, 6, 8])

In [23]:
y.shape

(27,)

# Train model

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
random_forest = RandomForestClassifier()

In [26]:
random_forest.fit(X_cv, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

# Testing

In [28]:
X_cv_test = cv.transform(["is your shop open today?"]).toarray()

In [29]:
X_cv_test

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1]])

In [30]:
random_forest.predict(X_cv_test)

array([4])